[package]
name = "dioxus_docs_site"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# dioxus-router = { path = "../../dioxus/packages/router", features = ["web"] }
# dioxus = { path = "../../dioxus/packages/dioxus" }
# dioxus-web = { path = "../../dioxus/packages/web" }
# dioxus-ssr = { path = "../../dioxus/packages/ssr" }
# fermi = { path = "../../dioxus/packages/fermi" }
dioxus-router = { version = "0.3", features = ["web"] }
dioxus = { version = "0.3" }
dioxus-web = { version = "0.3" }
dioxus-ssr = { version = "0.3" }
fermi = { version = "0.3" }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
log = "0.4.17"
wasm-logger = "0.2.0"
wasm-bindgen = { version = "0.2.86", features = ["enable-interning"] }
once_cell = "1.17.1"
console_error_panic_hook = "0.1.7"
gloo-history = "0.1.3"
autoexport = "0.1.0"
dioxus-material-icons = "1.1.0"


[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
