[package]
name = "dioxus_docs_site"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-router = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes" }
dioxus = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes" }
dioxus-web = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes", features = ["hydrate"], optional = true }
dioxus-ssr = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes", optional = true }
dioxus-fullstack = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes", features = ["router"] }
dioxus-tui = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes", optional = true }
dioxus-desktop = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes", optional = true }
dioxus-liveview = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes", features = ["axum"], optional = true }
dioxus-native-core = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes", optional = true }
dioxus-native-core-macro = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes", optional = true }
fermi = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes" }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
log = "0.4.17"
wasm-logger = "0.2.0"
wasm-bindgen = { version = "0.2.86", features = ["enable-interning"] }
once_cell = "1.17.1"
console_error_panic_hook = "0.1.7"
gloo-history = "0.1.3"
autoexport = "0.1.0"
dioxus-material-icons = { git = "https://github.com/jkelleyrtp/dioxus-material-icons", branch = "jk/bump-release" }
include_dir = "0.7.3"
anyhow = "1.0.71"
syntect-html = { git = "https://github.com/demonthos/include_mdbook", branch = "router-intigration" }
mdbook-shared = { git = "https://github.com/demonthos/include_mdbook", branch = "router-intigration" }
use-mdbook = { git = "https://github.com/demonthos/include_mdbook", branch = "router-intigration" }

dioxus-search = { git = "https://github.com/dioxuslabs/dioxus-search" }

tokio = { version = "1.29.0", features = ["full"], optional = true }
axum = { version = "0.6.12", optional = true }
simple_logger = "4.2.0"
shipyard = { version = "0.6.2", optional = true }
reqwest = { version = "0.11.18", features = ["json"] }
gloo-storage = { version = "0.2.2", optional = true }
web-sys = { version = "0.3.64", features = ["Document", "Window", "Event", "AddEventListenerOptions"] }
slab = "0.4.8"
chrono = { version = "0.4.26", features = ["serde"] }
futures = "0.3.28"
async-recursion = "1.0.4"
futures-util-preview = "0.2.2"
pretty_assertions = { version = "1.4.0", optional = true }

[profile.release]
# lto = true
# codegen-units = 1
opt-level = 'z'
strip = "debuginfo"

[patch.crates-io]
dioxus-core = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes" }
dioxus-rsx = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes" }
dioxus = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes" }

[patch."https://github.com/dioxuslabs/dioxus"]
dioxus-router = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes" }
dioxus-core = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes" }
dioxus-rsx = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes" }
dioxus = { git = "https://github.com/demonthos/dioxus", branch = "reject-external-routes" }

[features]
default = []
doc_test = ["tokio", "ssr", "dioxus-web", "dioxus-router/web", "dioxus-tui", "dioxus-desktop", "dioxus-liveview", "dioxus-native-core", "dioxus-native-core-macro", "shipyard", "gloo-storage", "pretty_assertions"]
web = ["dioxus-web", "dioxus-router/web"]
ssr = ["dioxus-ssr", "dioxus-router/ssr", "tokio", "dioxus-fullstack/axum", "axum"]
prebuild = ["ssr"]
