[package]
name = "dioxus_docs_site"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-router = { path = "../dioxus/packages/router" }
dioxus = { path = "../dioxus/packages/dioxus" }
dioxus-web = { path = "../dioxus/packages/web", features = ["hydrate"], optional = true }
dioxus-ssr = { path = "../dioxus/packages/ssr", optional = true }
dioxus-fullstack = { path = "../dioxus/packages/fullstack", features = ["router"] }
fermi = { path = "../dioxus/packages/fermi" }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
log = "0.4.17"
wasm-logger = "0.2.0"
wasm-bindgen = { version = "0.2.86", features = ["enable-interning"] }
once_cell = "1.17.1"
console_error_panic_hook = "0.1.7"
gloo-history = "0.1.3"
autoexport = "0.1.0"
dioxus-material-icons = "1.1.0"
include_dir = "0.7.3"
anyhow = "1.0.71"
mdbook-shared = { path = "../include_mdbook/mdbook-shared" }
use-mdbook = { path = "../include_mdbook/use-mdbook" }
tokio = { version = "1.29.0", features = ["full"], optional = true }
axum = { version = "0.6.12", optional = true }
simple_logger = "4.2.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[patch.crates-io]
dioxus-core = { path = "../dioxus/packages/core" }

[features]
default = []
web = ["dioxus-web", "dioxus-router/web"]
ssr = ["dioxus-ssr", "dioxus-router/ssr", "tokio", "dioxus-fullstack/axum", "axum"]
