name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - uses: actions-rs/install@v0.1
        with:
          crate: dioxus-cli
          version: latest
          use-tool-cache: true
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: dioxus build --release && cp dist/index.html dist/404.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          target-folder: docs
          clean: false # don't scrub docs
